language: swift
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCrypto.xcodeproj
    - IOS_SDK=iphonesimulator12.1
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.1
    - WATCHOS_SDK=watchsimulator5.1
    - CRYPTO_FRAMEWORK_NAME=VirgilCrypto
  matrix:
    - DESTINATION="OS=12.1,name=iPhone SE"                   PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                              PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=12.1,name=Apple TV 4K"                 PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm"  PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"   SWIFT_LINT="NO"
    - DESTINATION=""                                         PREFIX=""         SDK=""              BUILD="0"  PUBLISH_CARTHAGE="YES"  PUBLISH_POD="YES"  PUBLISH_DOCS="YES"  SWIFT_LINT="YES"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices

script:
  - carthage version
  - carthage bootstrap

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi

  - SCHEME="VirgilCrypto ${PREFIX}"

  - |
    if [ $BUILD == "2" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Run Tests
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
    elif [ $BUILD == "1" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
      carthage archive;
    fi
  
  # Generate and publish docs
  - if [ -n "${TRAVIS_TAG}" ] && [ $PUBLISH_DOCS == "YES" ]; then
      ./CI/publish-docs.sh;
    fi

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "$CRYPTO_FRAMEWORK_NAME.framework.zip"
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-crypto-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  - provider: script
    script: bash CI/publish-cocoapods.sh
    on:
      tags: true
      condition: $PUBLISH_POD == "YES"

  # Upload docs to gh-pages
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local_dir: "docs"
    on:
      repo: VirgilSecurity/virgil-crypto-x
      tags: true
      condition: $PUBLISH_DOCS = "YES"