language: swift
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCryptoApiImpl.xcodeproj
    - IOS_SDK=iphonesimulator12.1
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.1
    - WATCHOS_SDK=watchsimulator5.1
    - CRYPTO_FRAMEWORK_NAME=VirgilCryptoApiImpl
  matrix:
    - DESTINATION="OS=12.1,name=iPhone SE"                   PREFIX="iOS"      SDK="$IOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"  CARTHAGE_PLATFORM_NAME="iOS"      RUN_TESTS="YES"  PUBLISH_CARTHAGE="NO"   POD_LIB_LINT="NO"   SWIFT_LINT="NO"
    # - DESTINATION="arch=x86_64"                              PREFIX="macOS"    SDK="$MACOS_SDK"    TWO_STEP_BUILD_ENABLED="YES"  CARTHAGE_PLATFORM_NAME="Mac"      RUN_TESTS="YES"  PUBLISH_CARTHAGE="YES"  POD_LIB_LINT="NO"   SWIFT_LINT="NO"
    # - DESTINATION="OS=12.1,name=Apple TV 4K"                 PREFIX="tvOS"     SDK="$TVOS_SDK"     TWO_STEP_BUILD_ENABLED="YES"  CARTHAGE_PLATFORM_NAME="tvOS"     RUN_TESTS="YES"  PUBLISH_CARTHAGE="NO"   POD_LIB_LINT="NO"   SWIFT_LINT="YES"
    # - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm"  PREFIX="watchOS"  SDK="$WATCHOS_SDK"  TWO_STEP_BUILD_ENABLED="NO"   CARTHAGE_PLATFORM_NAME="watchOS"  RUN_TESTS="NO"   PUBLISH_CARTHAGE="NO"   POD_LIB_LINT="NO"  SWIFT_LINT="NO"

before_install:
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices

script:
  - carthage version
  - carthage bootstrap

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi

  - SCHEME="VirgilCryptoApiImpl ${PREFIX}"

  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current --no-use-binaries;
    fi
  
  # Check pod lib
  - if [ $POD_LIB_LINT == "YES" ]; then
      gem install cocoapods --pre;
      pod repo update;
      pod lib lint VirgilCryptoApiImpl.podspec;
    fi

before_deploy:
  - carthage archive

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "$CRYPTO_FRAMEWORK_NAME.framework.zip"
    skip_cleanup: true
    on:
      repo: VirgilSecurity/virgil-crypto-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"